[package]
name = "toolpouch-image"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kamadak-exif = "0.6.1"
image = { version = "0.25.10", default-features = false, features = [
    "bmp",
    "gif",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "tiff",
    "webp",
] }
